//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string SID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string DoctorID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> IntTime { get; set; }
    }
}
