//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Labconn_PKVuDucEntities : DbContext
    {
        public Labconn_PKVuDucEntities()
            : base("name=Labconn_PKVuDucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_0AutoUP> tbl_0AutoUP { get; set; }
        public virtual DbSet<tbl_0Config> tbl_0Config { get; set; }
        public virtual DbSet<tbl_0licence> tbl_0licence { get; set; }
        public virtual DbSet<tbl_AutoSeq> tbl_AutoSeq { get; set; }
        public virtual DbSet<Tbl_Calculator> Tbl_Calculator { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Config> tbl_Config { get; set; }
        public virtual DbSet<Tbl_Config_ReturnResult> Tbl_Config_ReturnResult { get; set; }
        public virtual DbSet<tbl_ConvertResult> tbl_ConvertResult { get; set; }
        public virtual DbSet<Tbl_CriticalAlarm> Tbl_CriticalAlarm { get; set; }
        public virtual DbSet<Tbl_Diagnostic> Tbl_Diagnostic { get; set; }
        public virtual DbSet<tbl_Doctor> tbl_Doctor { get; set; }
        public virtual DbSet<tbl_Function> tbl_Function { get; set; }
        public virtual DbSet<tbl_Group> tbl_Group { get; set; }
        public virtual DbSet<tbl_GroupTest> tbl_GroupTest { get; set; }
        public virtual DbSet<Tbl_Header> Tbl_Header { get; set; }
        public virtual DbSet<tbl_HISConnection_Trace> tbl_HISConnection_Trace { get; set; }
        public virtual DbSet<tbl_InsTest> tbl_InsTest { get; set; }
        public virtual DbSet<tbl_Instest_HIS> tbl_Instest_HIS { get; set; }
        public virtual DbSet<tbl_Instrument> tbl_Instrument { get; set; }
        public virtual DbSet<tbl_Intepreter> tbl_Intepreter { get; set; }
        public virtual DbSet<tbl_Inter> tbl_Inter { get; set; }
        public virtual DbSet<tbl_InterfacePara> tbl_InterfacePara { get; set; }
        public virtual DbSet<tbl_Location> tbl_Location { get; set; }
        public virtual DbSet<tbl_Location_L1> tbl_Location_L1 { get; set; }
        public virtual DbSet<tbl_Location_L2> tbl_Location_L2 { get; set; }
        public virtual DbSet<Tbl_Lock> Tbl_Lock { get; set; }
        public virtual DbSet<tbl_Log> tbl_Log { get; set; }
        public virtual DbSet<Tbl_Log_his> Tbl_Log_his { get; set; }
        public virtual DbSet<tbl_ModuleLicence> tbl_ModuleLicence { get; set; }
        public virtual DbSet<tbl_Object> tbl_Object { get; set; }
        public virtual DbSet<tbl_Object_Test> tbl_Object_Test { get; set; }
        public virtual DbSet<tbl_Patient> tbl_Patient { get; set; }
        public virtual DbSet<tbl_Patient_His> tbl_Patient_His { get; set; }
        public virtual DbSet<tbl_Patient_His_2012> tbl_Patient_His_2012 { get; set; }
        public virtual DbSet<tbl_Patient_His_2013> tbl_Patient_His_2013 { get; set; }
        public virtual DbSet<tbl_PatientLog> tbl_PatientLog { get; set; }
        public virtual DbSet<Tbl_PNormalRange> Tbl_PNormalRange { get; set; }
        public virtual DbSet<tbl_Profile> tbl_Profile { get; set; }
        public virtual DbSet<tbl_ProfileTest> tbl_ProfileTest { get; set; }
        public virtual DbSet<tbl_Protocol> tbl_Protocol { get; set; }
        public virtual DbSet<tbl_QC> tbl_QC { get; set; }
        public virtual DbSet<tbl_Reagent> tbl_Reagent { get; set; }
        public virtual DbSet<tbl_Result> tbl_Result { get; set; }
        public virtual DbSet<tbl_Result_His> tbl_Result_His { get; set; }
        public virtual DbSet<tbl_Result_His_2012> tbl_Result_His_2012 { get; set; }
        public virtual DbSet<tbl_Result_His_2013> tbl_Result_His_2013 { get; set; }
        public virtual DbSet<tbl_Result_OUT> tbl_Result_OUT { get; set; }
        public virtual DbSet<tbl_Result_OUT_his> tbl_Result_OUT_his { get; set; }
        public virtual DbSet<tbl_Result_Out_Tracking> tbl_Result_Out_Tracking { get; set; }
        public virtual DbSet<Tbl_Result_Upload> Tbl_Result_Upload { get; set; }
        public virtual DbSet<Tbl_Result_Upload_HIS> Tbl_Result_Upload_HIS { get; set; }
        public virtual DbSet<Tbl_SendTest> Tbl_SendTest { get; set; }
        public virtual DbSet<Tbl_Sendtest_His> Tbl_Sendtest_His { get; set; }
        public virtual DbSet<tbl_TestCode> tbl_TestCode { get; set; }
        public virtual DbSet<tbl_TestCode_HIS> tbl_TestCode_HIS { get; set; }
        public virtual DbSet<tbl_TestCode_Reagent> tbl_TestCode_Reagent { get; set; }
        public virtual DbSet<Tbl_TestCodeHIS> Tbl_TestCodeHIS { get; set; }
        public virtual DbSet<Tbl_TestType> Tbl_TestType { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_User_QuickCode> tbl_User_QuickCode { get; set; }
        public virtual DbSet<tbl_UserCategory> tbl_UserCategory { get; set; }
        public virtual DbSet<tbl_UserFunction> tbl_UserFunction { get; set; }
        public virtual DbSet<tbl_UserInstrument> tbl_UserInstrument { get; set; }
        public virtual DbSet<tbl_WorkOrder> tbl_WorkOrder { get; set; }
        public virtual DbSet<tbl_WorkOrder_His> tbl_WorkOrder_His { get; set; }
        public virtual DbSet<VS_Tbl_Antibiotic> VS_Tbl_Antibiotic { get; set; }
        public virtual DbSet<VS_Tbl_Bacterium> VS_Tbl_Bacterium { get; set; }
        public virtual DbSet<VS_Tbl_Bacterium_Antibiotic> VS_Tbl_Bacterium_Antibiotic { get; set; }
        public virtual DbSet<VS_Tbl_Bacterium_Group> VS_Tbl_Bacterium_Group { get; set; }
        public virtual DbSet<VS_Tbl_Microbe> VS_Tbl_Microbe { get; set; }
        public virtual DbSet<VS_Tbl_Object_Sample> VS_Tbl_Object_Sample { get; set; }
        public virtual DbSet<VS_Tbl_PBacterium> VS_Tbl_PBacterium { get; set; }
        public virtual DbSet<VS_Tbl_PBacterium_HIS> VS_Tbl_PBacterium_HIS { get; set; }
        public virtual DbSet<VS_Tbl_PSample> VS_Tbl_PSample { get; set; }
        public virtual DbSet<VS_Tbl_PSample_HIS> VS_Tbl_PSample_HIS { get; set; }
        public virtual DbSet<VS_Tbl_Result_Antibiotic> VS_Tbl_Result_Antibiotic { get; set; }
        public virtual DbSet<VS_Tbl_Result_Antibiotic_HIS> VS_Tbl_Result_Antibiotic_HIS { get; set; }
        public virtual DbSet<VS_Tbl_Sample> VS_Tbl_Sample { get; set; }
        public virtual DbSet<VS_Tbl_Sample_Type> VS_Tbl_Sample_Type { get; set; }
        public virtual DbSet<Result_out> Result_out { get; set; }
        public virtual DbSet<Tbl_Instest_Del> Tbl_Instest_Del { get; set; }
        public virtual DbSet<Tbl_Instest_Log> Tbl_Instest_Log { get; set; }
        public virtual DbSet<Tbl_Order_HIS> Tbl_Order_HIS { get; set; }
        public virtual DbSet<tbl_Order_HIS_HIS> tbl_Order_HIS_HIS { get; set; }
        public virtual DbSet<tbl_Patient_Del> tbl_Patient_Del { get; set; }
        public virtual DbSet<tbl_Result_Del> tbl_Result_Del { get; set; }
        public virtual DbSet<Tbl_TestCode_Del> Tbl_TestCode_Del { get; set; }
        public virtual DbSet<Tbl_TestCode_Log> Tbl_TestCode_Log { get; set; }
        public virtual DbSet<tbl_Unicode> tbl_Unicode { get; set; }
        public virtual DbSet<Tbl_UserSystem> Tbl_UserSystem { get; set; }
    }
}
