//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Object_Test
    {
        public string ObjectID { get; set; }
        public string TestCode { get; set; }
        public double Cost { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual tbl_Object tbl_Object { get; set; }
        public virtual tbl_TestCode tbl_TestCode { get; set; }
    }
}
