//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Intepreter
    {
        public int AutoID { get; set; }
        public string String1 { get; set; }
        public string String2 { get; set; }
        public Nullable<int> InsID { get; set; }
        public string TestCodeIN { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
