//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WorkOrder
    {
        public int AutoID { get; set; }
        public System.DateTime InsertTime { get; set; }
        public Nullable<System.DateTime> DownTime { get; set; }
        public System.DateTime DateIN { get; set; }
        public string PID { get; set; }
        public string SID { get; set; }
        public string TestcodeO { get; set; }
        public string TestCodeIN { get; set; }
        public int InsID { get; set; }
        public string PName { get; set; }
        public string Type { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
