//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PNormalRange
    {
        public int AutoID { get; set; }
        public string TestCode { get; set; }
        public Nullable<int> FromAge { get; set; }
        public Nullable<int> ToAge { get; set; }
        public bool PSex { get; set; }
        public string PNormalRange { get; set; }
        public Nullable<double> PLowerlimit { get; set; }
        public Nullable<double> PHigherlimit { get; set; }
        public System.Guid rowguid { get; set; }
        public bool Child { get; set; }
    }
}
