//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserSystem
    {
        public int AutoID { get; set; }
        public string UserSys { get; set; }
        public string PasswordSys { get; set; }
        public System.DateTime Intime { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
