//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TestCode_Del
    {
        public int AutoID { get; set; }
        public string TestCode { get; set; }
        public string QuickCode { get; set; }
        public string TestName { get; set; }
        public string Category { get; set; }
        public Nullable<double> Price { get; set; }
        public string NormalRange { get; set; }
        public string NormalRangeF { get; set; }
        public string Unit { get; set; }
        public Nullable<byte> PrintOrder { get; set; }
        public Nullable<bool> TestHead { get; set; }
        public string NormalResult { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> HigherLimit { get; set; }
        public Nullable<bool> Profile { get; set; }
        public Nullable<bool> Bold { get; set; }
        public string UserI { get; set; }
        public string UserD { get; set; }
        public Nullable<System.DateTime> Intime { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
        public Nullable<bool> Stat { get; set; }
        public string Criteria { get; set; }
        public Nullable<bool> LowHigh { get; set; }
        public Nullable<double> LHVal { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Optional { get; set; }
        public string BLLower { get; set; }
        public string BLHigher { get; set; }
        public string HigherID { get; set; }
        public Nullable<double> ConvertionNo { get; set; }
        public string NormalRange1 { get; set; }
        public string NormalRangeF1 { get; set; }
        public string Unit1 { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<byte> Align { get; set; }
        public string BarcodeType { get; set; }
        public string Boundary { get; set; }
        public byte DeltaType { get; set; }
        public Nullable<double> HigherWarning { get; set; }
        public Nullable<double> LowerWarning { get; set; }
        public string NormalRangeWarning { get; set; }
        public string NormalRangeWarningF { get; set; }
        public string Range { get; set; }
        public Nullable<bool> ResultBold { get; set; }
        public Nullable<byte> ResultFontSize { get; set; }
        public Nullable<bool> SendTest { get; set; }
        public string TestCodeHIS { get; set; }
        public Nullable<byte> TestNameFontSize { get; set; }
        public int Validity { get; set; }
        public Nullable<bool> NotPrint { get; set; }
        public Nullable<int> ExcludeGroup { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> PrintGroup { get; set; }
    }
}
