//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConvertResult
    {
        public int InsID { get; set; }
        public string TestCodeIn { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public string LoweValue { get; set; }
        public Nullable<double> HigherLimit { get; set; }
        public string HigherValue { get; set; }
        public Nullable<byte> Round { get; set; }
        public bool CampreOrCal { get; set; }
        public string Calculator { get; set; }
        public Nullable<double> ValueIs { get; set; }
        public string Note { get; set; }
        public System.DateTime Intime { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
