//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TestCode_Reagent
    {
        public string TestCode { get; set; }
        public string ReagentID { get; set; }
        public int InsID { get; set; }
        public Nullable<decimal> Consumption { get; set; }
        public string Note { get; set; }
        public string UserI { get; set; }
        public string UserU { get; set; }
        public Nullable<System.DateTime> Intime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual tbl_Instrument tbl_Instrument { get; set; }
        public virtual tbl_Reagent tbl_Reagent { get; set; }
        public virtual tbl_TestCode tbl_TestCode { get; set; }
    }
}
