//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doctor
    {
        public string DoctorID { get; set; }
        public string DoctorName { get; set; }
        public string DoctorHIS { get; set; }
        public System.Guid rowguid { get; set; }
        public string DoctorQuickCode { get; set; }
        public bool Optional { get; set; }
    }
}
