//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Diagnostic
    {
        public string DiagID { get; set; }
        public string Description { get; set; }
        public string DiagHIS { get; set; }
        public System.DateTime Intime { get; set; }
        public string DiagQuickCode { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
