//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Calculator
    {
        public string TestKey { get; set; }
        public string TestCodeKey { get; set; }
        public string TestCode1 { get; set; }
        public string TestCode2 { get; set; }
        public string TestCode3 { get; set; }
        public string TestCode4 { get; set; }
        public string Formular { get; set; }
        public System.DateTime Intime { get; set; }
        public System.Guid rowguid { get; set; }
        public string TestCode5 { get; set; }
    }
}
