//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Object()
        {
            this.tbl_Object_Test = new HashSet<tbl_Object_Test>();
            this.VS_Tbl_Object_Sample = new HashSet<VS_Tbl_Object_Sample>();
        }
    
        public string ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectHIS { get; set; }
        public System.Guid rowguid { get; set; }
        public string ObjectQuickCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Object_Test> tbl_Object_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VS_Tbl_Object_Sample> VS_Tbl_Object_Sample { get; set; }
    }
}
