//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HISConnection_Trace
    {
        public int AutoID { get; set; }
        public System.DateTime TimeExec { get; set; }
        public string SQLAction { get; set; }
        public string OutputResult { get; set; }
        public string CallOwner { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
