//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TestCode_HIS
    {
        public int AutoID { get; set; }
        public string TestCodeHIS { get; set; }
        public string TestName { get; set; }
        public string Unit { get; set; }
        public string Testcode { get; set; }
        public string profileID { get; set; }
        public System.DateTime Intime { get; set; }
        public string UserU { get; set; }
        public string Type { get; set; }
        public string TestCodeHead { get; set; }
        public string SampleID { get; set; }
        public string BacteriumID { get; set; }
        public string AntibioticID { get; set; }
        public System.Guid rowguid { get; set; }
        public string MasterID { get; set; }
    
        public virtual tbl_Profile tbl_Profile { get; set; }
        public virtual tbl_TestCode tbl_TestCode { get; set; }
    }
}
