//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Config
    {
        public string ConfigID { get; set; }
        public string Value { get; set; }
        public string Note { get; set; }
        public System.DateTime InTime { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
