//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Config_ReturnResult
    {
        public int AutoID { get; set; }
        public string TestCode { get; set; }
        public Nullable<byte> DayGet { get; set; }
        public Nullable<System.DateTime> TimeGet { get; set; }
        public Nullable<byte> DayReturn { get; set; }
        public Nullable<System.DateTime> TimeReturn { get; set; }
        public Nullable<int> DaySet { get; set; }
        public string Note { get; set; }
        public string UserIn { get; set; }
        public System.DateTime Intime { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
