//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Instest_HIS
    {
        public int AutoID { get; set; }
        public int InsID { get; set; }
        public string TestCode { get; set; }
        public string TestcodeIN { get; set; }
        public bool AllowInsert { get; set; }
        public string Type { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public bool Inside { get; set; }
        public bool LonNho { get; set; }
        public bool Omit { get; set; }
        public bool VALhigher { get; set; }
        public bool VALlower { get; set; }
        public string UserD { get; set; }
        public Nullable<System.DateTime> Intime { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual tbl_Instrument tbl_Instrument { get; set; }
    }
}
