//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_UserCategory = new HashSet<tbl_UserCategory>();
            this.tbl_UserFunction = new HashSet<tbl_UserFunction>();
            this.tbl_UserInstrument = new HashSet<tbl_UserInstrument>();
        }
    
        public string UserID { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public byte GroupID { get; set; }
        public System.Guid rowguid { get; set; }
        public bool DefaultS { get; set; }
        public byte[] Signature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserCategory> tbl_UserCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserFunction> tbl_UserFunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserInstrument> tbl_UserInstrument { get; set; }
    }
}
