//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Log_his
    {
        public int AutoID { get; set; }
        public string SID { get; set; }
        public string TestCode { get; set; }
        public string Result { get; set; }
        public byte ActionID { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public string UserU { get; set; }
        public Nullable<System.DateTime> ResultUpdateTime { get; set; }
        public System.Guid rowguid { get; set; }
        public string UserID { get; set; }
    }
}
