//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Location_L2
    {
        public string LocationID { get; set; }
        public string LocationName { get; set; }
        public string Location_L1 { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
