//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Header
    {
        public string Hospital { get; set; }
        public string Lab { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ResultTitle { get; set; }
        public string Chief { get; set; }
        public string LabID { get; set; }
        public System.Guid rowguid { get; set; }
        public string PosSign { get; set; }
        public string ChiefOfBill { get; set; }
        public string PosSignOfBill { get; set; }
    }
}
