//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Instest_Del
    {
        public int AutoID { get; set; }
        public Nullable<int> InsID { get; set; }
        public string TestCode { get; set; }
        public string TestcodeIN { get; set; }
        public Nullable<bool> AllowInsert { get; set; }
        public string Type { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<bool> Inside { get; set; }
        public Nullable<bool> LonNho { get; set; }
        public Nullable<bool> Omit { get; set; }
        public Nullable<bool> VALhigher { get; set; }
        public Nullable<bool> VALlower { get; set; }
        public string UserD { get; set; }
        public Nullable<System.DateTime> Deltime { get; set; }
        public Nullable<double> LowLimit { get; set; }
        public string LowValue { get; set; }
        public Nullable<double> HighLimit { get; set; }
        public string HighValue { get; set; }
        public Nullable<byte> Round { get; set; }
        public Nullable<bool> Quantity { get; set; }
        public Nullable<bool> Quality { get; set; }
        public Nullable<bool> Stat { get; set; }
        public string TestCodeIn2 { get; set; }
        public Nullable<bool> OrtherNMR { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
