//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Instrument()
        {
            this.tbl_InsTest = new HashSet<tbl_InsTest>();
            this.tbl_Instest_HIS = new HashSet<tbl_Instest_HIS>();
            this.tbl_TestCode_Reagent = new HashSet<tbl_TestCode_Reagent>();
            this.tbl_UserInstrument = new HashSet<tbl_UserInstrument>();
        }
    
        public int InsID { get; set; }
        public string ProtocolID { get; set; }
        public string InsName { get; set; }
        public bool AutoValidate { get; set; }
        public string ConType { get; set; }
        public System.Guid rowguid { get; set; }
        public string InsIDHIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InsTest> tbl_InsTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Instest_HIS> tbl_Instest_HIS { get; set; }
        public virtual tbl_Protocol tbl_Protocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TestCode_Reagent> tbl_TestCode_Reagent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserInstrument> tbl_UserInstrument { get; set; }
    }
}
