//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CriticalAlarm
    {
        public int AutoID { get; set; }
        public string SID { get; set; }
        public string PatientName { get; set; }
        public string TestCode { get; set; }
        public string TestName { get; set; }
        public string Result { get; set; }
        public string OrderID { get; set; }
        public int Color { get; set; }
        public string TestCodeHIS { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
