//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inter
    {
        public string PID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string LocationID { get; set; }
        public System.DateTime DateIN { get; set; }
        public System.DateTime Intime { get; set; }
        public string Address { get; set; }
        public string UserI { get; set; }
        public string UserU { get; set; }
        public int AutoID { get; set; }
        public string ObjectID { get; set; }
        public System.Guid rowguid { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int ChildAge { get; set; }
    }
}
