//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient_His_2013
    {
        public string SID { get; set; }
        public string PatientName { get; set; }
        public string Seq { get; set; }
        public Nullable<System.DateTime> Intime { get; set; }
        public System.DateTime DateIN { get; set; }
        public string Sex { get; set; }
        public string DoctorID { get; set; }
        public string LocationID { get; set; }
        public string ObjectID { get; set; }
        public string Diagnostic { get; set; }
        public Nullable<int> Age { get; set; }
        public bool PrintOut { get; set; }
        public bool FullResult { get; set; }
        public bool ReturnResult { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public string PID { get; set; }
        public string UserI { get; set; }
        public int AutoID { get; set; }
        public string Invoice { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public string UserD { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Comment { get; set; }
        public bool Valid { get; set; }
        public string Bed { get; set; }
        public string OrderID { get; set; }
        public string PDoctorName { get; set; }
        public System.Guid rowguid { get; set; }
        public string Resultcount { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string CommentVS { get; set; }
        public Nullable<System.DateTime> DateGet { get; set; }
        public string DoctorCom { get; set; }
        public bool Download { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FullTime { get; set; }
        public string PDescription { get; set; }
        public string Phone { get; set; }
        public int PrintCount { get; set; }
        public bool Urgent { get; set; }
        public int UrgentTime { get; set; }
        public Nullable<System.DateTime> ValidTime { get; set; }
        public string Room { get; set; }
        public bool Child { get; set; }
        public int ChildAge { get; set; }
        public bool KSK { get; set; }
    }
}
