//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QC
    {
        public int AutoID { get; set; }
        public System.DateTime RunDate { get; set; }
        public int QCNgay { get; set; }
        public int QCtruc { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public string UserU { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
