//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TestCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TestCode()
        {
            this.tbl_GroupTest = new HashSet<tbl_GroupTest>();
            this.tbl_InsTest = new HashSet<tbl_InsTest>();
            this.tbl_Object_Test = new HashSet<tbl_Object_Test>();
            this.tbl_ProfileTest = new HashSet<tbl_ProfileTest>();
            this.tbl_TestCode_HIS = new HashSet<tbl_TestCode_HIS>();
            this.tbl_TestCode_Reagent = new HashSet<tbl_TestCode_Reagent>();
            this.tbl_User_QuickCode = new HashSet<tbl_User_QuickCode>();
        }
    
        public string TestCode { get; set; }
        public string QuickCode { get; set; }
        public string TestName { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
        public string NormalRange { get; set; }
        public string NormalRangeF { get; set; }
        public string Unit { get; set; }
        public Nullable<byte> PrintOrder { get; set; }
        public bool TestHead { get; set; }
        public string NormalResult { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> HigherLimit { get; set; }
        public bool Profile { get; set; }
        public bool Bold { get; set; }
        public string UserI { get; set; }
        public string UserU { get; set; }
        public Nullable<System.DateTime> Intime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public bool Stat { get; set; }
        public string Criteria { get; set; }
        public bool LowHigh { get; set; }
        public Nullable<double> LHVal { get; set; }
        public string Type { get; set; }
        public bool Optional { get; set; }
        public System.Guid rowguid { get; set; }
        public byte Align { get; set; }
        public string BarcodeType { get; set; }
        public string BLHigher { get; set; }
        public string BLLower { get; set; }
        public string Boundary { get; set; }
        public double ConvertionNo { get; set; }
        public byte DeltaType { get; set; }
        public int ExcludeGroup { get; set; }
        public bool GetInsName { get; set; }
        public string HigherID { get; set; }
        public Nullable<double> HigherWarning { get; set; }
        public string InsUse { get; set; }
        public Nullable<double> LowerWarning { get; set; }
        public string MaXN { get; set; }
        public string Method { get; set; }
        public string NormalRange1 { get; set; }
        public string NormalRangeF1 { get; set; }
        public string NormalRangeWarning { get; set; }
        public string NormalRangeWarningF { get; set; }
        public string Range { get; set; }
        public bool ResultBold { get; set; }
        public byte ResultFontSize { get; set; }
        public bool SendTest { get; set; }
        public string TestCode_OLD { get; set; }
        public string TestCodeHIS { get; set; }
        public byte TestNameFontSize { get; set; }
        public string Unit1 { get; set; }
        public int Validity { get; set; }
        public bool NotPrint { get; set; }
        public int PrintType { get; set; }
        public int PrintGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupTest> tbl_GroupTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InsTest> tbl_InsTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Object_Test> tbl_Object_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProfileTest> tbl_ProfileTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TestCode_HIS> tbl_TestCode_HIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TestCode_Reagent> tbl_TestCode_Reagent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User_QuickCode> tbl_User_QuickCode { get; set; }
    }
}
