//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Unicode
    {
        public int AutoID { get; set; }
        public string Unicode { get; set; }
        public string VNI { get; set; }
        public System.Guid rowguid { get; set; }
        public string Unsign { get; set; }
    }
}
