//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_Tbl_PBacterium_HIS
    {
        public int AutoID { get; set; }
        public string SID { get; set; }
        public string SampleID { get; set; }
        public string BacteriumID { get; set; }
        public string BacteriumName { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public string OrderID { get; set; }
        public string BacteriumHIS { get; set; }
        public Nullable<bool> ESBL { get; set; }
        public bool DTEST { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
