//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_Tbl_PSample_HIS
    {
        public int AutoID { get; set; }
        public string SID { get; set; }
        public string SampleID { get; set; }
        public string SampleName { get; set; }
        public double Price { get; set; }
        public double Cost { get; set; }
        public string ResultCulture { get; set; }
        public string Result { get; set; }
        public int PrintOrder { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public string UserU { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string UserUCulture { get; set; }
        public Nullable<System.DateTime> UpdatetimeCulture { get; set; }
        public string OrderID { get; set; }
        public string SampleHIS { get; set; }
        public System.Guid rowguid { get; set; }
        public string STypeID { get; set; }
    }
}
