//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_Tbl_Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VS_Tbl_Sample()
        {
            this.VS_Tbl_Object_Sample = new HashSet<VS_Tbl_Object_Sample>();
        }
    
        public string SampleID { get; set; }
        public string SampleName { get; set; }
        public double Cost { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public int PrintOrder { get; set; }
        public System.Guid rowguid { get; set; }
        public string Method { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VS_Tbl_Object_Sample> VS_Tbl_Object_Sample { get; set; }
    }
}
