//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_Tbl_Antibiotic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VS_Tbl_Antibiotic()
        {
            this.VS_Tbl_Bacterium_Antibiotic = new HashSet<VS_Tbl_Bacterium_Antibiotic>();
        }
    
        public string AntibioticID { get; set; }
        public string AntibioticName { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VS_Tbl_Bacterium_Antibiotic> VS_Tbl_Bacterium_Antibiotic { get; set; }
    }
}
