//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_Tbl_Bacterium_Antibiotic
    {
        public string BacteriumID { get; set; }
        public string AntibioticID { get; set; }
        public Nullable<double> LowInside { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> HighInside { get; set; }
        public Nullable<double> LowInsideMIC { get; set; }
        public Nullable<double> LowMIC { get; set; }
        public Nullable<double> HighMIC { get; set; }
        public Nullable<double> HighInsideMIC { get; set; }
        public string LowInsideStr { get; set; }
        public string LowHighStr { get; set; }
        public string HighInsideStr { get; set; }
        public string LowInsideMICStr { get; set; }
        public string LowHighMICStr { get; set; }
        public string HighInsideMICStr { get; set; }
        public string Unit { get; set; }
        public string UnitMIC { get; set; }
        public string UserI { get; set; }
        public System.DateTime Intime { get; set; }
        public string ExternalCode { get; set; }
        public string HISCode { get; set; }
        public bool ESBLChange { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual VS_Tbl_Antibiotic VS_Tbl_Antibiotic { get; set; }
        public virtual VS_Tbl_Bacterium VS_Tbl_Bacterium { get; set; }
    }
}
