//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuDucLapConnClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_Tbl_Microbe
    {
        public int AutoID { get; set; }
        public string QuickCode { get; set; }
        public string MicroName { get; set; }
        public string UserI { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
